### PR TITLE
483112 angular 15

### PR DESCRIPTION
**Pull request by corykon**

### CODE REVIEW

**Review by andrew-frueh — APPROVED** [review]

**Comment by corykon** [comment]
@andrew-frueh We have some failing unit tests. Will have to look more at this after the break.

- Failing tests in `@BindObservable`, which was added for cell resizing. Cell resizing is in fact broken when you test this branch. (`projects/cashmere/src/lib/table/bind-observable/bind-observable.spec.ts`)
- Failing tests in the scrollnav, but I don't see any bugs on the component (`projects/cashmere/src/lib/scroll-nav/content/scroll-nav-target.directive.spec.ts`)

**Comment by corykon** [comment]
@aaronbrethorst @cikeddy when you have chance, could you guys give this angular 15 upgrade a look? want to get some extra eyes on this with @andrew-frueh out

**Comment by cikeddy** [comment]
Screen Shot 2023-07-14 at 10 14 49 AM

Seems like the styles on images aren't coming through properly. Attaching a screenshot from the healthcare.ai page.

**Comment by cikeddy** [comment]
Also seeing a styling issues on the date-range section. 
Screen Shot 2023-07-14 at 10 48 41 AM

**Comment by corykon** [comment]
@cikeddy thank you! Got those fixed.

**Comment by cikeddy** [comment]
Screen Shot 2023-07-14 at 12 09 14 PM

I'm seeing this error for the picklist component.

**Review by cikeddy — APPROVED** [review]
Put all the issues I found in comments—looked good to me otherwise!

**Comment by aaronbrethorst** [comment]
I didn't notice anything other than what Cass has already pointed out. Great work!

**Comment by corykon** [comment]
Thanks for the review!!

**Pull request merged**
