### PR TITLE
Demo page improvement (landing page with some reorganization)

### PR DESCRIPTION
**Pull request by nickrflynn**
It's not pretty yet but it's a step towards something like [https://material.angular.io/](https://material.angular.io/)

(#17 - demo page needs improvement)

### CODE REVIEW

**Comment by benjanderson** [comment]
I like the organization and the direction. I think we need some sort of global navigation even if its just the home page and the components. Its a little disorienting to be thrown into the components page without a way back

**Comment by andrew-frueh** [comment]
Cool, good start @nickrflynn.  One small change I would suggest: can you give your <h2> line a font-weight of 300?  So it looks like the attached image.
screen shot 2018-01-19 at 5 09 08 pm

**Comment by nickrflynn** [comment]
I know @benjanderson used https://material.angular.io/ as an example but do we have something else more specific in terms of a vision/mock up for the demo @andrew-frueh?

**Comment by andrew-frueh** [comment]
Nope, nothing more specific than https://material.angular.io/ at the moment.  I'll give some more thought to content for this landing page.  But as far as the browsing experience for the actual components, I think the Angular spec is a great target.  Ultimately, we want this page to replace our style guide PDF.  Let's discuss this more at our next Cashmere Open Space meeting.

**Comment by andrew-frueh** [comment]
Cool - changes look good @nickrflynn.  So @benjanderson - I know we're still working out our governance but for straight forward updates like this can we say if it gets UX signoff and a technical signoff from someone like yourself we can merge?  There is plenty more we'll want to do on the demo page, but I'm assuming the goal isn't to leave pull requests open forever.  Seems like the intent of this one was to introduce a landing page - and thumbs up from me on what Nick has checked in.

**Comment by benjanderson** [comment]
Good point @andrew-frueh, this is a great incremental change. I will approve this knowing its just a base

**Comment by andrew-frueh** [comment]
@benjanderson I added an approval of my own for posterity.  So what is standard practice now - is "Squash and Merge" usually the best way to merge to reduce the list of commits?  Or is that not a big deal?

**Comment by benjanderson** [comment]
I don't have a strong opinion on whether to squash or not. Currently on my team we never squash to keep a better history and merges can be easier. However I can see the benefit of a squash with such a simple change like this. 

I do feel that the person who created the pull request should complete it

**Comment by andrew-frueh** [comment]
Cool, that works for me @benjanderson - makes sense to me to not squash for the sake of preserving history.  And I also like the idea of the person submitting the pull request having the satisfaction of merging it.  So take it away @nickrflynn - go ahead an hit that big shiny merge button :-)

**Comment by nickrflynn** [comment]
I actually can't complete it: `Only those with write access to this repository can merge pull requests.`

**Comment by benjanderson** [comment]
you should have been sent an email or you can go here
https://github.com/HealthCatalyst/Fabric.Cashmere/invitations

**Pull request merged**
