### PR TITLE
fix(date range): smoother ui

### LINKED ISSUE #1244: Calendar Date Picker locks me from picking the next month of data
I ran a report for March then wanted to switch it to April but the controls blocked me. This needs to throw in an error in red at Apply time rather than locking the calendar browsing arrows.

image

### PR DESCRIPTION
**Pull request by corykon**
warn about date range being invalid on save, instead of locking the ui while selecting dates

fix #1244

### CODE REVIEW

**Comment by andrew-frueh** [comment]
Out of curiosity, will this fix resolve the issue #1287 that @jonest just submitted?

**Comment by corykon** [comment]
I’ve haven’t dug in enough to know, but my guess would be no...

**Comment by corykon** [comment]
@jonest  @andrew-frueh looks like it should fix #1288 though!

**Pull request merged**
