### PR TITLE
docs(mobile guildlines): new section

### PR DESCRIPTION
**Pull request by andrew-frueh**
Thanks for your patience on this one @aaronbrethorst  and @corykon.  Opening this PR with the initial migration of Aaron's word doc into content for the site.  New section is added to the navigation and new docs are added to the search indexing.  Still several things to complete before it's ready to merge (Cory - I'm hoping you and I can split the writing):

- [x] Mobile Navigation Section @andrew-frueh 
- [x] Form Fields @andrew-frueh 
- [x] Add references/links from existing component docs to mobile guidelines @andrew-frueh 
- [x] Modals/Popovers/Drawers @corykon 
- [x] Help Text @corykon 

Admittedly I'm also questioning the readability of our text on the site now looking at these pages.  The Cashmere site wasn't designed with large blocks of text in mind, and as I compare it to docs.healthcatalyst.com, I wonder if we should consider some improvements.  But that's a job for another day.

Once the above tasks are complete, I think we'll have a pretty good first pass at this section that we can start circulating around to other folks at Catalyst for feedback.  I should have my two sections written by end of day tomorrow.

### CODE REVIEW

**Review by corykon — APPROVED** [review]
I think we've got an awesome start here :+1:

**Comment by aaronbrethorst** [comment]
Yeah, this looks great. Thanks for taking care of converting it to Markdown, Andrew!

**Comment by andrew-frueh** [comment]
Thanks @aaronbrethorst & @corykon, I'll get those last two todos knocked out after my meetings this morning and then we'll get this one merged and out for folks to review!  Cory I'll also review your Angular 12 PR this afternoon too.

**Comment by andrew-frueh** [comment]
Alright got those last items completed.  Gonna give it one more proof-read tomorrow morning and then get this merged.

**Pull request merged**
