### PR TITLE
Add Github link to navbar

### PR DESCRIPTION
**Pull request by nickrflynn**

### CODE REVIEW

**Comment by nickrflynn** [comment]
Small piece of #17 (Cashmere Demo Page)

**Comment by benjanderson** [comment]
Its a tragedy we couldn't use the navbar-icon element to do this. When you check this in I may try to modify the navbar to work with this

**Comment by jtrujill** [comment]
@benjanderson What does the navbar-icon do? Could we just modify the navbar so that it styles the hc-icon the same as the navbar-icon

**Comment by nickrflynn** [comment]
Done @andrew-frueh

**Pull request merged**
