### PR TITLE
521 convert picklist to mixins

### LINKED ISSUE #521: (Opt-in) Convert the Picklist component
https://github.com/HealthCatalyst/Fabric.Cashmere/blob/7adc22557ba90a5e17433225e776d4c4e35526af/guides/using-and-customizing-components.md

### PR DESCRIPTION
**Pull request by isaaclyman**
Fixes #521

### CODE REVIEW

**Comment by isaaclyman** [comment]
Failing check due to:

```
npm ERR! code ENEEDAUTH
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-05-15T20_46_50_888Z-debug.log
The command "./scripts/travis-script.sh" exited with 1.
```

All the build/test tasks succeeded.

**Comment by corykon** [comment]
@andrew-frueh I've got the same issue with my PR, looks like the new build step that publishes @next (a preview/pre-release version of the library) is having auth problems. We could probably merge this and be just fine since nothing else fails beforehand.

**Comment by andrew-frueh** [comment]
okay @corykon - I'll go ahead and merge and cross my fingers.  And maybe @joeskeen can take a look at that build issue when he has a chance.

**Pull request merged**
