### PR TITLE
Fixes #211 - select acts as a block element

### LINKED ISSUE #211: hc-select acts as block element
hc-select acts like a block element which isn't expected. The hc-select element should have `display: inline-block` applied to the host element. Instead of having the `<span class="chevron"></span>` wrap the native select element, a padding should be applied to the right side so that the chevron can be absolutely positioned there.

Related to #203

### PR DESCRIPTION
**Pull request by jtrujill**
This has the same fix as PR #212 so if this gets accepted I'll close that

### CODE REVIEW

**Comment by jtrujill** [comment]
I removed an input called highlight since it seemed to want to do the same thing that all inputs that implement ControlValueAccessor. When you use angular forms and an input implements ControlValueAccessor it'll add the appropriate classes ng-invalid, ng-dirty, ng-pristine... based on the state of the control.

This would be the more appropriate way to implement the functionality that hightlight provided. I would actually want to change the styling in the future so that we can create a simple forms.scss which styles all ng-invalid control appropriately

**Comment by joeskeen** [comment]
@jtrujill #212 has been merged, do you need to revisit this?

**Comment by jtrujill** [comment]
I'll update this PR so that it has those changes

**Comment by jtrujill** [comment]
Updated

**Pull request merged**
