### PR TITLE
feat(modal): the component can now be resized

### LINKED ISSUE #647: Draggable and resizable modals
**Describe the problem this feature request is solving**
We use modals in our app that are draggable and resizable. Probably won't be able to switch to cashmere modals until this functionality is added, or there's a way to plugin this type of functionality.

**Describe the solution you'd like**
New parameters, `isDraggable` to make the modal draggable by its title bar, and `isResizable` to make it resizable from the bottom right corner.

**Describe alternatives you've considered**
Find this a way to plugin this functionality on my own without forcing this functionality in Cashmere... but seems like lots of apps could benefit from this work.

**If any, which components will have to change, and how**
Modal component. No breaking changes, just new functionality.

**Additional context**
Screenshot from our app, draggable by title, resizable by bottom right corner.
image

### PR DESCRIPTION
**Pull request by WistyDagel**
When setting the isResiable property to true, the modal can be resized by the user.

closes #647

### CODE REVIEW

**Comment by corykon** [comment]
Code wise looks like a good approach! I am seeing a linting issue failing the build:
image

Tip to try and avoid those kind of build failures - It's a good idea to run `npm run lint` before you check in so can catch those ahead of time.

**Review by corykon — APPROVED** [review]

**Review by andrew-frueh — CHANGES_REQUESTED** [review]
More nice work here @WistyDagel - finally got to pull this down and play around with it.  A few things I'd like to discuss and see if we can clean up for a merge on this one:

1. Would be ideal if we could add some kind of constraints on the resizing, so that it can't be shrunk past a minimum width.  Right now you can shrink it down to a teeny tiny modal that kind of feels like a mistake.
2. As the modal is resized it - will no longer be centered on the screen.  Maybe our best bet here is to _only_ allow the modal to be resized vertically.  That will help with item one above and will also eliminate any centering issues.  That's actually what GitHub does with this input text box I'm typing in now.
3. I'm pretty sure I remember you saying that resize and draggable don't play nicely with each other.  Wondering if we can brainstorm a way to get them both working - if jQuery UI can do it, I bet we can too :-)  And if not, let's make sure it fails gracefully and only allows one to be set at a time (so nothing is broken).  And let's make sure the documentation explains if you can only use one or the other.

**Comment by corykon** [comment]
@andrew-frueh My thoughts on your 3 suggestions-
1. Totally agree. We have min-widths on resizable modals in PB
2. Losing centering hasn't bothered me on PB, and if it does, you can just drag it back to the center. 
3. Really would be a bummer to not have the two work together. I'd support pressing pause on this CSS approach to see if we can find a javascript based method to make things work the way really want. Even if we have to fork/borrow/steal from the jquery codebase

**Comment by andrew-frueh** [comment]
@corykon - agreed on your second point, provided that dragging & resizing can work together :-) if they can't, then you just end up with a really big off-center modal.  So yeah, I'm with you on item number 3, let's crank on this one a little more and see if we can get both drag and resize on the same modal.  Then I won't be so worried about the off-center problem.

**Review by andrew-frueh — CHANGES_REQUESTED** [review]
@WistyDagel looks like you've got one small linting error and a few failing unit tests (related to changing css classes).  Looking forward to reviewing live today!

**Comment by andrew-frueh** [comment]
Updated PR coming with corrected dev branch merge

**Pull request closed without merging**
