### PR TITLE
refactor(hc-table): update hc-table styles to match official designs

### PR DESCRIPTION
**Pull request by isaaclyman**
This PR proposes changes to the hc-table to bring it into alignment with @andrew-frueh's designs (https://xd.adobe.com/view/55c8964a-fe2f-41c3-4ede-3d1bbd4d5b71-23f9/screen/ea040736-2e21-46f1-a57e-20275e50b077/Expense-Region/). It also adds a footer row to the Example Overview Table in the documentation to better demonstrate the functionality and style of footer rows.

### CODE REVIEW

**Comment by andrew-frueh** [comment]
This looks great @isaaclyman - thanks for doing this.  Can you make one small addition to the css file?  I noticed on the "Styles" page for tables that the sorting indicator classes were getting their borders cut off in the header.  So on line 161 of tables.scss, in the hc-col-sortable class, can you add `background-clip: padding-box;`.  That will made sure the borders appear above the background even with position:relative turned on.

@corykon @benjanderson - some design thoughts on this.  Something I observed pretty much across the board in our user tests was that many users weren't entirely sure if they could sort a table based on the column with the styling I favored before (no borders around the header).  I think removing a border around the header made them think it was static, even if a sorting indicator was there.  So even though I prefer the no border look in the header row, I'm thinking that for usability - it's probably better to include it.  But of course we'll have to see if this change proves out with actual users.

**Comment by andrew-frueh** [comment]
And just for anyone that was wondering, the table sorting indicator in the component still needs to be updated as per this issue: https://github.com/HealthCatalyst/Fabric.Cashmere/issues/412

**Comment by isaaclyman** [comment]
@andrew-frueh Thanks for pointing that out, I've added a commit.

**Pull request merged**
