### PR TITLE
add lists to typography guidelines

### PR DESCRIPTION
**Pull request by cedar-ave**
To close [#144](https://github.com/HealthCatalyst/Fabric.Cashmere/issues/144).
I formatted one of the files in VS Code without realizing it would show up as a bunch of changes - sorry.

### CODE REVIEW

**Comment by cedar-ave** [comment]
Good point - that would work. The thinking behind the separation is that the font size and padding in tables is smaller and tighter than in body text. At least, I think it looks a lot better and is more readable that way. We have a ton of tables in the docs and some of the cells can get hefty. I noticed Microsoft does the same thing (see body text at the top, then the table beneath)

2018-03-13 16_50_27-understanding azure virtual machine usage _ microsoft docs

In the DOS docs site, these are our regular bullets

2018-03-13 16_46_33-protect entities and bindings from unauthorized schema changes _ articles - mic

These are our table bullets

2018-03-13 16_46_19-protect entities and bindings from unauthorized schema changes _ articles - mic

But I see your point and don't want to clutter up the style guide for no reason.

**Comment by andrew-frueh** [comment]
Makes sense @cedar-ave - and I definitely like the different styles for article lists in tables as opposed to paragraphs.  Maybe for the sake of the demo tile, we just show an example of the tile version.  But we add a sentence to the top of the tile that describes the differences in font-size and padding for lists in tables vs paragraphs.

**Comment by cedar-ave** [comment]
@andrew-frueh I love this solution. I did this and also explained the `<article>` tag.

**Comment by cedar-ave** [comment]
I forgot to add the comments about tables being more compact - will do that now

**Pull request merged**
