### PR TITLE
fix(navbar): allow keyboard accessibility

### PR DESCRIPTION
**Pull request by corykon**
- popover anchor with a trigger of "click" can be opened by enter key when that anchor has focus
- tweak styles for anchor links and icons when focused
- updated examples to illustrate proper tabindex settings in the navbar

re #1361

### CODE REVIEW

**Comment by corykon** [comment]
@joeskeen @andrew-frueh Can this get a review? Would love to get this merged in for the next release. I've got a bug on the pop builder board that this will unblock for me

**Review by andrew-frueh — CHANGES_REQUESTED** [review]
Hey @corykon - everything looks good in Chrome, but unfortunately in Firefox the tabindex seems to skip navbar items and go straight to the "more" dropdown.  Can you test this out in Firefox to see if you get the same results?

**Review by andrew-frueh — APPROVED** [review]
@corykon pointed me here:
https://stackoverflow.com/questions/3846868/why-wont-tabindex-work-with-firefox

Looks like it's a Firefox / MacOS issue

**Pull request merged**
