### PR TITLE
build(bit): remove bit

### PR DESCRIPTION
**Pull request by aaronbrethorst**
BREAKING CHANGE: apps previously using the ChangeCasePipe should now use the change-case npm package
directly

re #1750

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
I'm going to hold this PR open a little longer. @corykon noticed a couple small nits that should get fixed in this before it lands. Cory - what's your preferred way to get those changes added? Shall I merge and have you do a quick follow-up fix, or would you prefer something else?

**Comment by corykon** [comment]
@aaronbrethorst I'd love to submit those little tweaks to this PR, hoping to push that in today. If I don't get there though... go ahead and merge!

**Comment by andrew-frueh** [comment]
I haven't yet @corykon - I'll try that now

**Pull request merged**
