### PR TITLE
Picklist

### LINKED ISSUE #61: Picklist
Much credit to @corykon and the Population Builder team for developing a pattern that has been followed by a number of apps.  The picklist is called upon when a user needs to select a number of items from a potentially length list of options.  Although the picklist component would most commonly be used within a #40 modal dialog, it can stand alone as well.  Cory, I know I've already dropped the massive "table" component on your plate, but since you set the standard here, I think you'd be the most qualified to componentize this.

picklist

### PR DESCRIPTION
**Pull request by corykon**
Huge PR. Let me know if anyone wants to sit down and do a walkthrough with me.

Constructed it so that it'll work for PopBuilder, and hopefully for others, too. Supports cases as simple as just passing an array of strings to choose from, to passing in callback functions that handle paged server requests across values and value sets.

Closes #61

### CODE REVIEW

**Comment by joeskeen** [comment]
@corykon could we set up a time tomorrow to go over this?  I'll take a look at it tonight.

**Comment by andrew-frueh** [comment]
Great idea @joeskeen - just sent out an invite for tomorrow.

**Comment by joeskeen** [comment]
I'm going to take some time in the next few days to give this a close look.  I should have a review by the end of the week.

**Comment by jtrujill** [comment]
You'll need to add an index file that follows all the other components

**Pull request merged**
