### PR TITLE
feat(date-range): make start & end dates optional

### LINKED ISSUE #1297: Date Range: Make "required" start & end dates configurable.
**New config point.** In pop builder, we need to the flexibility to set **_just_** the bottom or top of the range, so that the selection can read something like "6/4/2020 or earlier", or "4/1/2020 or later". That doesn't appear to be possible with this component. 

Whether or not nulls are allowed on either end of the range should be configurable. Could add a couple properties, default them to true. Something like:

- `startDateIsRequired`
- `endDateIsRequired`

### PR DESCRIPTION
**Pull request by aaronbrethorst**
Allows date ranges to be open-ended on either side to allow for selecting ranges like "Feb 24, 2022 or earlier" or "Feb 24, 2022 or later".

Closes #1297

### CODE REVIEW

**Review by corykon — APPROVED** [review]
Haven't run this locally, but the code looks spot on. Thanks a million @aaronbrethorst!

**Comment by aaronbrethorst** [comment]
thanks @corykon! This is the first time I've ever worked with Angular; I'm glad everything looks right :)

**Comment by aaronbrethorst** [comment]
@andrew-frueh would you mind taking a peek, too, before I merge?

**Comment by andrew-frueh** [comment]
Hey @aaronbrethorst - the code is excellent, nicely done!  The thing I just posted to our Slack channel was a question for the Vitalware team around whether we want to hide the second calendar if start/end is marked optional.  Or if both should still show, it's just a question of validation as to whether we accept a null state on a calendar.

**Review by andrew-frueh — CHANGES_REQUESTED** [review]
Okay confirmed with the Vitalware team that they'd actually like both calendars to always be visible (even if start/end are optional), but the picker will accept a null value in that case and clear validation.  Let me know if you have any questions on that

**Comment by aaronbrethorst** [comment]
Right on, thanks @andrew-frueh

**Comment by aaronbrethorst** [comment]
@andrew-frueh @corykon changes requested by Vitalware are up and this is ready for another review! I think there are future improvements that can/should be made around clearing dates on the start/end dates (right now you have to delete the contents of the textboxes), but that feels more like a strong 'nice to have' than a must-have. LMK if you disagree.

**Comment by corykon** [comment]
Just tested, this is looking good. Did find one more minor issue. If you open the picker from a state where one date is already not included, and you add and then remove the date, you'll get a little red error message that isn't needed. Might be worth ironing out if possible before we release.

488e0931-0114-4708-a0f8-7c5d985e3658

Other than that I think we're about good to go though - can work on a little button for quickly clearing out a date later. Prob something like this-
image

**Comment by aaronbrethorst** [comment]
@corykon OK, I think I finally have this sorted out 😅. I pushed up a fix for the problem you noted. Let me know if you'd like to see this implemented differently, or if you'd like me to squash it into the first commit.

**Review by corykon — APPROVED** [review]

**Comment by corykon** [comment]
This looks great @aaronbrethorst, went ahead and merged this in. Thanks again for your efforts on this one

**Pull request merged**
