### PR TITLE
fix(mobile ux): components no longer zoom on mobile

### LINKED ISSUE #1602: Mobile Zooming on Inputs
**Summary**

Currently our input form fields have a text size that is less than 16 px, which causes phones on iOS to zoom into the field when focused/clicked. We should probably set the text size to at least 16 px on mobile to fix this, but there are other possible solutions (see article in additional context section).

**Reproduction**

Steps to reproduce:

1. Navigate to Cashmere on an iPhone
2. Click any input field

Stackblitz reproduction (click the "Edit on Stackblitz" link on a component example and fork the template):

**Additional context**

Here's an article explaining this issue: https://www.warrenchandler.com/2019/04/02/stop-iphones-from-zooming-in-on-form-fields/

### PR DESCRIPTION
**Pull request by WistyDagel**
closes #1602

### CODE REVIEW

**Review by corykon — APPROVED** [review]

**Comment by andrew-frueh** [comment]
@corykon - any concern that these breakpoints increase the font size not only for mobile devices for _any_ smallish browser window?  Like if I'm on a laptop but have a smaller window, suddenly the fonts on my inputs will be way bigger.  Should we be looking for adding logic here to ensure this change happens only on mobile devices?

**Comment by corykon** [comment]
That’s a good point. What exactly is the breakpoint we’re using, and do we
expect desktop browser windows to actually get that small?

Getting logic just right for detecting whether the device is actually
“mobile” is tricky, and usually requires some JavaScript.

We could just keep the functionality out and instead include the
information somewhere in a guide for app teams to make the best decision
for their use case.

**Comment by corykon** [comment]
@andrew-frueh Sounds like we want to abandon this PR? If anything, the right solution might just be a guide explaining how to implement something similar if needed for a particular app's use case.

**Comment by andrew-frueh** [comment]
Agreed @corykon - I'm debating whether we should add a param called `mobile` (kind of like `tight`) that renders the input with the larger font size.  Having two separate params isn't great though - would be better to have something like `fieldStyle` with values of either `normal`, `tight`, or `mobile`.  And we could keep the `tight` param as something deprecated for a few releases.  Let's discuss tomorrow.

**Pull request closed without merging**
