### PR TITLE
Cashmere on Angular 8 Release

### PR DESCRIPTION
**Pull request by joeskeen**

### CODE REVIEW

**Comment by andrew-frueh** [comment]
@joeskeen - should this be a 7.0.0 release?  Because it's a breaking change if you aren't on Angular 8?

**Comment by joeskeen** [comment]
@andrew-frueh  correct - this will be a major release.  I did note that with a BREAKING CHANGE comment in my first commit.

**Comment by andrew-frueh** [comment]
Great - thanks @joeskeen

**Pull request merged**
