### PR TITLE
fix(mobile navbar): adjusted the ux for the mobile navbar

### LINKED ISSUE #1566: Table inside Drawer will not resize when the user zooms with their browser
**Summary**

This is a tough one to explain and demonstrate. I got the bug showing on stackblitz KINDA.  A better demonstration than the stackblitz is in the care management app so contact me if you want to see it.

When a table is used with the drawer, when the drawer is open and the the user zooms in, the table will overlap the area despite having a set width.  This doesn't happen in other areas without a drawer.

**Reproduction**

https://stackblitz.com/edit/drawer-with-table-overlfow?file=src/app/app.component.ts

**Additional context**

image

### LINKED ISSUE #1581: Navbar Mobile Redesign
We should align the hamburger icon to the left-hand side of the navbar, center / left-lean the logo, and have additional options on the right-hand side of the navbar. 

Hopefully, this will improve the user experience for Cashmere mobile and align the library with more current mobile web-based trends. 

For better context, 

Our current mobile navbar: 
image

Potential mobile navbar:
image
image

### PR DESCRIPTION
**Pull request by WistyDagel**
Moved the hamburger icon to the left, left-aligned the title, and expanded the ability for right-content
to show on tablets and larger mobile devices

closes #1581
closes #1566 

Before:
image

After (iPhone): 
image

(iPad):
image

### CODE REVIEW

**Comment by andrew-frueh** [comment]
@corykon @jacquie @robertjorg - @WistyDagel brought up a great question in regards to this PR.  If we allow for icons on the right side of the navbar in the `sm` responsive state - how would we expect the navbar to handle it when there are too many icons to fit?  In other words, what happens when that right container is too big?  

Should it just be `overflow: hidden` and it's up to the developer to not put too much in there?  Seems like we should allow it fail more gracefully than that.  Another option is to put an ellipsis menu (similar to what Material does) on the right side if the content is too large for the space, and it triggers another dropdown.

Would be curious to hear your thoughts on how you want the component to handle that scenario.

**Comment by andrew-frueh** [comment]
Quick follow up for the thread - we made a decision that to start, we'll just add `overflow: hidden` to the right container and leave it to the developers to ensure they aren't putting too much content onto the right side.  Possibly in the future we can look into wrapping the overflow more gracefully into a menu or something like that.

**Review by WistyDagel — COMMENTED** [review]
It looks like commitizen somehow merged the changes I had just made with the drawer and margin with the same pr I had made for the navbar... I don't know how this happened as I had created a whole new commitizen push and everything.

**Review by andrew-frueh — APPROVED** [review]
Just pulled the branch and ran locally - all the navbar updates look great.  Nice work!

**Pull request merged**
