### PR TITLE
build(angular 13): upgrade to newer version of angular

### PR DESCRIPTION
**Pull request by corykon**
Ran into all kinds of interesting little issues along the way. A summary of what I worked on:

- Update to angular 13
- Update ng-select, angular-tslint
- Remove explicit corejs dependency
- Fix npm i/build issues w/ rxjs in cashmere-examples
- Update angular/cdk to 13 and update getting started guide that mentions a specific version of the angular CDK
- Rip out IE
     - Update browserlist and polyfills
     - Update Browser support page
- Get rid of all the console warnings sbout CommonJS modules
- Convert from using "/" for division to using math.div in our sass files
- Fix scss files size budget warning

re #1714

### CODE REVIEW

**Review by andrew-frueh — APPROVED** [review]
Pending the decision on ChangeCasePipe - looks great to me

**Review by aaronbrethorst — APPROVED** [review]
Looks good to me!

**Comment by andrew-frueh** [comment]
@corykon I think we're ready to merge this one

**Pull request merged**
