### PR TITLE
feat(confirmation modal): add confirmation modal service

### PR DESCRIPTION
**Pull request by corykon**
Provide a minimal code experience for common modal use cases.

Just inject the ConfirmationModalService, and write a bit of code:

```

        this.confirmService
            .confirm({message: 'Are you sure you want to do XYZ?'})
            .pipe(
                take(1),
                filter(confirmed => confirmed)
            )
            .subscribe(() => {
                // go do the thing
            });
```

Also has a `confirmDestructive()` function with reasonable defaults for a destructive actions.

image

re #1706

### CODE REVIEW

**Comment by isaaclyman** [comment]
This is awesome. We've built a ConfirmationModalComponent for our app, but yours has all the same options we've got and then some.

Only one suggestion: could there be a `white-space: pre-wrap` on the modal body so that newlines in the `message` parameter are preserved, for easy multi-paragraph messages?

**Comment by corykon** [comment]
great idea @isaaclyman!

**Review by andrew-frueh — APPROVED** [review]
Looking great, well done @corykon - aside from that one small style tweak everything is good to go by me.  I did have a question about services - is it standard practice to make something like this a separate service, as opposed to wrapping it into the existing ModalService?  Is it better to keep services more modular?  I can certainly see instances where I'd need to pull both ModalService and ConfirmationService in my constructor, so that's mainly why I ask.

**Comment by andrew-frueh** [comment]
That's a good call @isaaclyman - I think that'd be a pretty simple addition to your `options` @corykon and it expands the use case here.

**Comment by andrew-frueh** [comment]
> > Looking great, well done @corykon - aside from that one small style tweak everything is good to go by me. I did have a question about services - is it standard practice to make something like this a separate service, as opposed to wrapping it into the existing ModalService? Is it better to keep services more modular? I can certainly see instances where I'd need to pull both ModalService and ConfirmationService in my constructor, so that's mainly why I ask.
> 
> Yeah, great question and a valid argument. I like to keep services (and all files, really) smaller, more modular, and focused on one job. Angular style guide talks about it a bit - https://angular.io/guide/styleguide#single-responsibility-1

Ah that Angular Style guide is really helpful.  And I think following that reasoning, you've done the right thing here 👍

**Comment by corykon** [comment]
@andrew-frueh @isaaclyman After adding support for alerts, should I rename the service to something more generic?

SimpleModalService
QuickModalService

Or just merge it into the standard ModalService like @andrew-frueh suggests?

**Comment by corykon** [comment]
@isaaclyman FYI I added a `preserveMessageWhitespace` parameter. I was going to default to true, but decided against it because it's easy to accidentally introduce an extra space if you're not anticipating it. Felt like defaulting to false would be the less surprising to most devs

**Pull request merged**
