### PR TITLE
docs(stackblitz): temporary stackblitz version fix

### PR DESCRIPTION
**Pull request by andrew-frueh**
Frustrating to have to do this - but I hate having broken Stackblitz links while we wait for a response from them.  What do you both think?

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
I think its better than leaving them broken!

**Review by corykon — APPROVED** [review]
Probably good to do this now. I realllly hope this doesn't last long though.

**Comment by andrew-frueh** [comment]
Agree with both of you.  I'll see if there is any way to escalate an issue with Stackblitz.  Tricky if we aren't paying them though.  I'll get this merged for now.

**Pull request merged**
