### PR TITLE
extract breadcrumbs styles and clean things up a little

### LINKED ISSUE #125: enhance breadcrumbs to support dynamic creation
Currently the bread crumbs component reads the routes to build itself. This works for a simple site, but most sites including Atlas will need the ability to have the breadcrumbs built dynamically. 

As an example, atlas uses metadata to build its routes/breadcrumbs. This is something we need supported
image

### PR DESCRIPTION
**Pull request by benjanderson**
- extract out breadcrumbs styles
- extract out subnav styles
- fix issue with breadcrumbs not setting initial state
- breadcrumbs style page + guide
closes #125

### CODE REVIEW

**Comment by jtrujill** [comment]
Why the need to extract the subnav and breadcrumb styles?

**Comment by benjanderson** [comment]
This was something we had talked a long time ago with issue #125, Atlas had some unique needs and the solution we came up with is to extract and reuse the styles, so at least we had some reuse.

I think the long term solution would be a custom breadcrumb resolver proposed in #236. But this is the first step

**Comment by jtrujill** [comment]
In the future it'd be best to have a PR for each issue so that things can be reviewed separately. What about the subnav?

**Comment by benjanderson** [comment]
Good point, I will separate pull requests in the future. The reason I extracted the styles from the subnav as well was because in the breadcrumb demo I was only using markdown, so I couldn't use the `<hc-subnav>` component. 

I also agreed with your comment where fixed-top could be easier solved in css. https://github.com/HealthCatalyst/Fabric.Cashmere/issues/243#issuecomment-388231621 This takes us one step closer.

**Comment by jtrujill** [comment]
We can worry about the fixed-top stuff in issue #243. I'll approve but I think this should be temporary like you said until we can get a better solution

**Pull request merged**
