### PR TITLE
889 sticky table headers

### LINKED ISSUE #1207: Sticky headers should not overlap table
When using the `sticky` property on the `hc-header-row`, table data is still scrolling underneath the header.
image
The fix I have come up with includes adding a background color of white to `.hc-table th` (or pink).
image
And to remove the still visible top pixel and edge borders use `border-collapse: separate;` on the `.hc-table`.
image

### PR DESCRIPTION
**Pull request by corykon**
We had a few really old issues out there about sticky table headers being buggy and not well documented. Now that we're not supporting IE11, this become easier.

**Component**
image

**CSS-only Examples**
image

re #889 
re #685 
fix #1207

### CODE REVIEW

**Comment by corykon** [comment]
Also have to mention that Github copilot is really fun with generating examples - it magically autocompleted all the stats and facts about the cities for me.

**Review by andrew-frueh — CHANGES_REQUESTED** [review]
Wow, nicely done - there is definitely some CSS alchemy in this one.  I know from past work on the table styles that it can be super finicky to pin down.  And I imagine it's even worse with the `sticky` display type.  Everything is looking good except when you have "borders" off, "header" on, and "column" off.  As you scroll, you can see the left border creeping up beside the top left cell (at least in Firefox).  See the attached screenshot.
 
Screenshot 2023-05-22 at 9 15 07 PM

**Comment by corykon** [comment]
Fixed that issue. Anything else you noticed?
sticky-headers

I added some styles for table on $slate-gray-100 background, since that's pretty standard.
stickytable-bgs

**Review by andrew-frueh — APPROVED** [review]

**Pull request merged**
