### PR TITLE
feat(navbar): navbar co-branding

### LINKED ISSUE #875: Need Co-branding available on the navbar
**Describe the problem this feature request is solving**
Our clients want to co-brand the HC applications and prominently display their logo on all the application, including leading wisely dashboards and reports.

**Describe the solution you'd like**
We want the Cashmere navbar to have a configurable section below the existing navbar to allow a user to co-brand by the addition of their logo and limited text or slogans

**Describe alternatives you've considered**
We have attempted to accommodate this within LW, but it does not address the consistency the client is looking for, nor does it allow the co-branded logo to be a prominent part of the NavBar

https://files.slack.com/files-pri/T04807US5-FJYPM5AQM/screen_shot_2019-05-23_at_4.28.22_pm.png
image

** If any, which components will have to change, and how **

-   Components changed?
Cashmere Navbar
-   Are these breaking changes to public interfaces?
Unknown

**Additional context**

### PR DESCRIPTION
**Pull request by andrew-frueh**
adds the ability to add a logo to the right side of the navbar

closes #875

### CODE REVIEW

**Review by corykon — APPROVED** [review]
Looks good! I have a few suggestions, not vital but worth considering:
- It would be clearer to me to name the component NavbarCobrandComponent
- Adding a drop shadow to the examples help it have a little more defined shape, esp when using the white background cobranding logo
- Having separate examples for cobranding and the app switcher would makes things easier to digest for devs

**Comment by andrew-frueh** [comment]
All good suggestions - will get those updates made.  Would you recommend naming the tag for the component `hc-navbar-cobrand` as well?

**Comment by corykon** [comment]
Yeah I like that

**Review by corykon — APPROVED** [review]

**Review by jacquie — APPROVED** [review]
Looks good to me 👍 
I agree with Cory about separate examples with and without the cobranding
Thanks - looking forward to incorporating it in LW

**Pull request merged**
