### PR TITLE
docs(personas): healthfinch personas

### PR DESCRIPTION
**Pull request by andrew-frueh**
@heathkat - I think I've got all of Amanda's HealthFinch personas changes & additions incorporated.  Can you do a review for me and validate that I got everything in from her Word doc correctly?

### CODE REVIEW

**Review by heathkat — COMMENTED** [review]
@andrew-frueh I made a few very small changes (removing extra spaces, periods, and adding text missing from a title). What's the best way to send you those changes? Create another branch off of your healthfinch-personas branch and do a PR?

**Comment by andrew-frueh** [comment]
thanks @heathkat - that's great.  Actually why don't you just do a commit and push it up to my branch.  Since it's in a PR already here you should have permissions to do that.  Then it'll automatically get included in this PR.  Slack me if you're having trouble pushing the commit.

**Review by heathkat — APPROVED** [review]

**Comment by andrew-frueh** [comment]
Thanks so much for the proofing @heathkat and pushing those changes

**Pull request merged**
