### PR TITLE
Angular 11

### LINKED ISSUE #1448: Upgrade to Angular 11
As per our [Angular support guidelines](https://cashmere.healthcatalyst.net/guides/supported-angular-versions), we'll be upgrading our dependency to Angular 11 on **May 11, 2021**.  The upgrade to 9/10 was harder than expected, so we'll probably want to get started on this in early June 2021.

### LINKED ISSUE #1541: Upgrade HC Table to CDK 11
**Describe your idea**

Our current CDK dependency is less than the most current version because the `hc-table` component was breaking when upgraded to version 11.

**What problem are you trying to solve?**

Want to make sure we continue to align with the latest versions of the CDK

### PR DESCRIPTION
**Pull request by andrew-frueh**
_Travis wasn't working anymore because I think we didn't select the Free plan officially.  Set that up so hopefully it'll trigger builds again._

@corykon I think I've got everything updated and building successfully with Angular 11 and the latest CDK. Please validate that you don't get any errors and give the site a once over to make sure everything is still running as expected. I guess we'll plan on getting the elint update done before we release v11, correct?

closes #1448
closes #1541

### CODE REVIEW

**Review by corykon — APPROVED** [review]

**Comment by corykon** [comment]
@andrew-frueh I was able to build and run this branch no problem. I'll plan to work on eslint in the next week or so.

I noticed we're getting a crazy high number of vulnerabilities reported by npm. I'll create an issue for that if there isn't one - 
image

**Comment by corykon** [comment]
@andrew-frueh how close is this to final?  I'd like to do eslint changes after this is merged into dev because I'll be making changes to deps in package.json

**Comment by andrew-frueh** [comment]
Hey @corykon - sorry was out of the office a few days, but just got back and noticed that unit tests are failing on Travis with a really strange error.  Didn't see that happening locally.  Might need your help or @joeskeen to try and figure out what's happening there so we can get that merged.  I'll ping you on Slack sometime today.

**Comment by andrew-frueh** [comment]
@corykon - I got those unit tests fixed so we've got a passing build now w/ Angular 11.  I'll get this merged to dev and kick it over to you to work on esLint as you have time.  Thanks!

**Pull request merged**
