### PR TITLE
style(formfields): border styles

### LINKED ISSUE #1211: Buggy styles for input borders (Firefox on windows)
Firefox on windows isn't handling the .5 inset shadow hack to create 1.5px borders:
image

### PR DESCRIPTION
**Pull request by andrew-frueh**
Changes all borders to 1px $slate-gray-300.

Give this one a look over @corykon and make sure I didn't miss anything.  Fortunately we have enough form-field examples across the site that I think I was able to adjust all the edge cases.

I'm definitely with you on the lighter color for select and input boxes.  I'm slightly nervous that checkboxes and radios are hard to see with the lighter color.  But I'm willing to give it go - and we hear from users that it's a problem we can always adjust.  I will say that after staring at the 1px version for the past hour, the 1.5 and 2px versions of the borders look REALLY fat :-)

closes #1211

### CODE REVIEW

**Comment by corykon** [comment]
@andrew-frueh How would you feel about keeping the checkbox/radio buttons 1px, then going with a slightly darker border for those with the shade or darken function?

I think they're probably ok as is, but having them a few shades darker feels good too, and doesn't jump out as inconsistent.

**Comment by corykon** [comment]
Should I create a new issue for adding focus states? Or any chance we can squeeze that in here too?

**Comment by andrew-frueh** [comment]
Hey @corykon I'd be interested in seeing what you think about the darker shade on the radios and checkboxes.  I tried making it a full color value darker and it looked a little too out of sync, but I didn't try just shades.

I'm hoping to get a release out today - and unfortunately I don't think I'll have time to add focus states.  So I'd probably add another issue unless you think you might have time to add to this PR.

**Comment by corykon** [comment]
@andrew-frueh Sorry I've been slow to get back to you on this. If we've got time, I would love to take a swing at adding focus and hover styles some time this week. Would be awesome to have them go out at the same time as the 1px border style updates

**Comment by andrew-frueh** [comment]
Okay @corykon - I think this one is ready to be merged.  I guess give it one more look and approve if you agree.  Huge step forward for Cashmere.

**Comment by andrew-frueh** [comment]
Travis build is passing:
https://travis-ci.org/github/HealthCatalyst/Fabric.Cashmere/builds/702210721

For some reason it isn't getting reported back, so I'll merge the PR.

**Pull request merged**
